version: '3.8'
networks:
  questt-network:
    driver: bridge

services:
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    restart: always
    ports:
      - '80:3000'
    networks: 
      - questt-network
  authentication:
    container_name: authentication
    build: ./authentication
    restart: always
    ports:
      - '8080:3000'
    depends_on:
      - auth-mongo
    networks: 
      - questt-network
  books:
    container_name: books
    build: ./books
    restart: always
    ports:
      - '8070:3000'
    depends_on:
      - books-mongo
    networks: 
      - questt-network
  auth-mongo:
    container_name: auth-mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./auth-data/datadir/mongo/data:/data/db
    networks: 
      - questt-network
  books-mongo:
    container_name: books-mongo
    image: mongo:latest
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./books-data/datadir/mongo/data:/data/db
    networks: 
      - questt-network