version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    restart: always
    ports:
      - '80:3000'
  authentication:
    container_name: authentication
    build: ./authentication
    restart: always
    ports:
      - '8080:3000'
  books:
    container_name: books
    build: ./books
    restart: always
    ports:
      - '8070:3000'
  # search:
  #   container_name: search
  #   build: ./Search
  #   restart: always
  #   ports:
  #     - '8060:3000'